{block #head}
<h2><span>Bonusy pro zaměstnance - zájezdy</span></h2>
{/block}

{block #content}

<table class="datagrid">
    <tr>
        <th>Název zájezdu</th>
        <th>Lokalita</th>
        <th>Informace</th>
        <th>Délka pobytu</th>
        <th>Hotel</th>
        <th>Cena</th>
        <th>Strava</th>
        <th>Typ zájezdu</th>
        <th>&nbsp;</th>
    </tr>

{foreach $zajezdy as $zajezd}
    <tr>
        <td>{$zajezd->nazev}</td>
        <td>{$zajezd->lokalita}</td>
        <td>{$zajezd->informace}</td>
        <td>{$zajezd->delkaPobytu}</td>
        <td>{$zajezd->hotel}</td>
        <td>{$zajezd->cena}</td>
        <td>{$zajezd->strava}</td>
        <td>{$zajezd->typZajezdu}</td>
        <td>
            <?php $zajezdId = (int) $zajezd->zajezdId; ?>
            {if @$orderedZajezdy[$zajezdId] > 0}
            <a href="{link cancelZajezd $orderedZajezdy[$zajezdId]}">Zrušit objednávku</a>
            {else}
            <a href="{link orderZajezd $zajezd->zajezdId, $zajezd->caId, $zajezd->cena}">Objednat</a>
            {/if}
        </td>
    </tr>
{/foreach}
</table>

{/block}
