<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Request Tracking System</title>
        <meta http-equiv="content-language" content="cs" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
        <link href="{$basePath}/css/admin/styles.css" rel="stylesheet" type="text/css" media="screen" />
        <!--[if lte IE 7]>
	<link href="{$basePath}/css/admin/styles_ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
        <!--[if lte IE 6]>
	<link href="{$basePath}/css/admin/styles_ie6.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
        <script type="text/javascript" src="{$basePath}/js/admin/jquery-1.2.6.min.js"></script>
        <script type="text/javascript" src="{$basePath}/js/admin/ui.js"></script>
    </head>

    <body>

        <div id="wrap">
            <div id="header">
                <h1><a class="bg" href="#" title="Home"></a>Manager 1.0</h1>
                {if isset($user)}
                <p id="status"><a href="{link User:userChange 1, $user->id}"><strong>{$user->firstName} {$user->surname}</strong></a>  |  <a href="{link User:userChange 2, $user->id}">Password</a> | <a href="{link User:logout}">Logout</a>.</p>
                {/if}
                <?php //TODO: Co je to HEAD??? ?>
		<?php //@{include #head} ?>
            </div>
            <div id="sidebar">

                {if isset($user)}

                <ul class="items">
                    <li>
                        <a href="#" title="Správa ticketů">Správa ticketů</a>
                        <ul>
                            <li><a href="#" title="Přidat nový ticket">Přidat nový ticket</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" title="Uživatelský panel">Uživatelský panel</a>
                        <ul>
                            <li><a href="#" title="Editovat profil">Editovat profil</a></li>
                        </ul>
                    </li>
                    <li class="subitems">
                        <a href="#" title="Nastavení">Nastavení</a>
                        <ul>
                            <li><a href="#" title="Časové pásmo">Časové pásmo</a></li>
                        </ul>
                    </li>

                </ul>

                {/if}

                <span class="clear"></span>
                <div id="redbox">
                    <h4>Request Tracking System<br />
                        {snippet flashMessage}
                        {foreach $flashes as $flash}<div class="flash">{$flash->message}</div>{/foreach}
                        {/snippet}
                    </h4>
                    <p>
                        <big>Copyright 2010</big>
				Build: 20101023
                    </p>
                </div>
            </div>
            <div id="content">
		@{include #content}
            </div>
            <div id="footer">
            </div>
        </div>

    </body>
</html>
