<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Request Tracking System</title>
        <meta http-equiv="content-language" content="cs" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
        <link href="{$basePath}/css/admin/styles.css" rel="stylesheet" type="text/css" media="screen" />
        <link rel="stylesheet" type="text/css" href="{$baseUri}css/confirmform.css" />
        <!--[if lte IE 7]>
	<link href="{$basePath}/css/admin/styles_ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
        <!--[if lte IE 6]>
	<link href="{$basePath}/css/admin/styles_ie6.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
        <script type="text/javascript" src="{$basePath}/js/admin/jquery-1.2.6.min.js"></script>
        <script type="text/javascript" src="{$basePath}/js/admin/ui.js"></script>

        <!-- custom CSS -->
        <link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.ui.all.css" type="text/css" />
        <link rel="stylesheet" media="screen" href="{$baseUri}css/screen.css" type="text/css" />
        <link rel="stylesheet" media="screen" href="{$baseUri}css/datagrid.css" type="text/css" />
        <link rel="stylesheet" media="screen" href="{$baseUri}css/ajax.css" type="text/css" />
        <link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />

        <!-- jQuery -->
        <script type="text/javascript" src="{$baseUri}js/jquery.min.js"></script>
        <script type="text/javascript" src="{$baseUri}js/jquery.ui.core.js"></script>
        <script type="text/javascript" src="{$baseUri}js/jquery.ui.datepicker.js"></script>
        <script type="text/javascript" src="{$baseUri}js/jquery.livequery.js"></script>

        <!-- custom JS -->
        <script src="{$baseUri}js/jquery.nette.js" type="text/javascript"></script>
        <script src="{$baseUri}js/datagrid.js" type="text/javascript"></script>
    </head>

    <body>

        <div id="wrap">
            <div id="header">
                <h1><a class="bg" href="#" title="Home"></a>Manager 1.0</h1>
                {if isset($user)}
                <p id="status">Přihlášen <a href="{link User:userChange 1, $user->id}"><strong>{$user->firstName} {$user->surname}</strong></a>  |  <a href="{link User:userChange 2, $user->id}">Změnit heslo</a> | <a href="{link User:logout}">Odhlásit</a></p>
                {/if}

                {include #head}

            </div>
            <div id="sidebar">

                {if isset($user)}

                <ul class="items">
                    <li>
                        <a href="#" title="Správa ticketů">Správa tiketů</a>
                        <ul>
                            <li><a href="{link Ticket:myTickets}" title="Moje tikety">Moje tikety</a></li>
                            <li><a href="{link Ticket:}" title="Nepřiřazené tikety">Nepřiřazené tikety</a></li>
                            <li><a href="{link Ticket:closedTickets}" title="Uzavřené tikety">Uzavřené tikety</a></li>
                            <li><a href="{link Ticket:addTicket}" title="Přidat nový tiket">Přidat nový tiket</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" title="Uživatelský panel">Uživatelský panel</a>
                        <ul>
                            <li><a href="{link User:userChange 1, $user->id}" title="Editovat profil">Editovat profil</a></li>
                            <li><a href="{link User:userChange 2, $user->id}" title="Změnit heslo">Změnit heslo</a></li>
                        </ul>
                    </li>
                    <li class="subitems">
                        <a href="#" title="Nastavení">Nastavení</a>
                        <ul>
                            <li><a href="#" title="Časové pásmo">Časové pásmo</a></li>
                        </ul>
                    </li>
                    <li class="subitems">
                        <a href="#" title="Nastavení">Správa uživatelů</a>
                        <ul>
                            <li><a href="{link User:}" title="Přehled uživatelů">Přehled uživatelů</a></li>
                            <li><a href="{link User:userChange}" title="Nový uživatel">Nový uživatel</a></li>
                        </ul>
                    </li>

                </ul>

                {/if}

                <span class="clear"></span>
                <div id="redbox">
                    <h4>Request Tracking System</h4>
                    <p>
                        <big>Copyright 2010</big>
                        Martin Venuš<br />
                        Jaroslav Líbal<br />
                        Andrey Chervinka
                    </p>
                </div>
            </div>
            <div id="content">
                {*
                <p class="alert">
                    <span class="txt"><span class="icon"></span><strong>Alert:</strong> This template is going to explote in 10 seconds.</span>
                    <a href="#" class="close" title="Close"><span class="bg"></span>Close</a>

                </p>
                <p id="tip" class="alert">
                    <span class="txt"><span class="icon"></span><strong>Tip:</strong> I know, you REALLY love this CMS Skin.</span>
                    <a href="#" class="close" title="Close"><span class="bg"></span>Close</a>
                </p>
                *}

                {snippet flashMessage}
                {foreach $flashes as $flash}
                <p id="congrats" class="alert">
                    <span class="txt"><span class="icon"></span><strong>{$flash->message}</strong></span>
                    <a href="#" class="close" title="Close"><span class="bg"></span>Close</a>
                </p>
                {/foreach}
                {/snippet}

		@{include #content}
            </div>
            <div id="footer">
            </div>
        </div>

    </body>
</html>
