{block content}

    <?php $form->render('begin') ?><br />
    <?php $form->render('errors') ?>

    <!-- hidden fields -->
    <div n:foreach="$form->getComponents(TRUE, 'Nette\Forms\HiddenField') as $control">{$control->control}</div>

    <div class="lab">
        {!$form['name']->label}<br />
        {!$form['email']->label}<br />
        {!$form['mobile']->label}<br />
        {!$form['departmentId']->label}<br />
        {!$form['subject']->label}<br />
        {!$form['ticketMessage']->label}<br />
    </div>
    <div>
        {!$form['name']->control}<br />
        {!$form['email']->control}<br />
        {!$form['mobile']->control}<br />
        {!$form['departmentId']->control}<br />
        {!$form['subject']->control}<br />
        {!$form['ticketMessage']->control}<br />
    </div>
    <div class="but">{!$form['ok']->control}</div>
</form>

{/block}