<?php
$form['userName']->getControlPrototype()->class = "small";
$form['password']->getControlPrototype()->class = "small";
$form['login']->getControlPrototype()->class = "button";
?>

{block #content}

<?php $form->render('begin') ?>
<br />
<?php $form->render('errors') ?>

<fieldset>
    <legend>Zadejte prosím své přihlašovací údaje</legend>
    <table>
        <tr>
            <th>{!$form['userName']->label}</th>
            <td>{!$form['userName']->control}</td>
        </tr>
        <tr>
            <th>{!$form['password']->label}</th>
            <td>{!$form['password']->control}</td>
        </tr>
        <tr>
            <td style="text-align:center;" colspan="2">{!$form['login']->control}</td>
        </tr>
    </table>
</fieldset>
</form>

{/block}

{block #head}
<br /><br /><br />
<h2><span>Nejste přihlášeni</span></h2>
<p>Pro plné využití systému musíte být přihlášeni.</p>
{/block}