@{block content}

<fieldset>
    <legend>&nbsp;<strong>Uživatel</strong>&nbsp;</legend>
    <table>
        <tr>
            <th>Předmět:</th>
            <td>{$detaily->subject}</td>
        </tr>
        <tr>
            <th>Autor:</th>
            <td>{$detaily->name}</td>
        </tr>
        <tr>
            <th>IP adresa:</th>
            <td>{$detaily->ipAddress}</td>
        </tr>
        <tr>
            <th>E-mail/telefon:</th>
            <td>{$detaily->email} &nbsp;&nbsp;/&nbsp;&nbsp; {$detaily->phone}</td>
        </tr>
    </table>
</fieldset>

<fieldset>
    <legend>&nbsp;<strong>Ticket</strong>&nbsp;</legend>
    <table>
        <tr>
            <th>Status:</th>
            <td>{$detaily->status}</td>
        </tr>
        <tr>
            <th>Priorita:</th>
            <td>{$detaily->priority}</td>
        </tr>
        <tr>
            <th>Přiřazeno zaměstnanci:</th>
            <td>
                {if isset($zamestnanci[$detaily->staffId])}
                {$zamestnanci[$detaily->staffId]}
                {else}
                -
                {/if}
            </td>
        </tr>
        <tr>
            <th>Datum přidání:</th>
            <td>{$detaily->created|datumCas}</td>
        </tr>
        <tr>
            <th>Datum poslední změny:</th>
            <td>{$detaily->updated|datumCas}</td>
        </tr>
    </table>
</fieldset>

<fieldset n:if="$detaily->staffId!=NULL">
    <legend>&nbsp;<strong>Akce</strong>&nbsp;</legend>
    <table>
        <tr>
            <th><a href="{link Ticket:addReply, $detaily->id, 0}" title="Odpovědět">Odpovědět</a></th>
        </tr>
        <tr>
            <th><a href="{link Ticket:addReply, $detaily->id, 1}" title="Interní poznámka">Přidat interní poznámku</a></th>
        </tr>
        <tr>
            <th><a href="{link Ticket:forwardTicket, $detaily->id}" title="Předat tiket kolegovi z oddělení">Předat tiket kolegovi z oddělení</a></th>
        </tr>
        <tr>
            <th><a href="{link Ticket:changeDepartment, $detaily->id}" title="Předat tiket do oddělení">Předat tiket do jiného oddělení</a></th>
        </tr>
        <tr>
            <th>Změnit status tiketu</th>
        </tr>
    </table>
</fieldset>

<fieldset n:if="$detaily->staffId==NULL">
    <legend>&nbsp;<strong>Akce</strong>&nbsp;</legend>
    <table>
        <tr>
            <th><a href="{link Ticket:takeTicket, $detaily->id}" title="Přijmout tiket mezi své">Přijmout tiket mezi své</a></th>
        </tr>
    </table>
</fieldset>

{foreach $zpravy as $zprava}
<fieldset>
    <legend>&nbsp;<strong>{$zprava->name}{if ($zprava->name == $detaily->name)} (autor tiketu){/if}</strong>, {$zprava->date|datumCas}&nbsp;</legend>
    <p>
        {$zprava->message}
    </p>
</fieldset>
{/foreach}

{/block}

{block #head}
<h2><span>Detaily tiketu č. {$detaily->ticketID}</span></h2>
{/block}
